[package]
name = "frame-android"
version = "0.1.0"
edition = "2021"

[dependencies]
frame-core = { path = "../frame-core" }
slotmap = "1"

[target.'cfg(target_os = "android")'.dependencies]
frame-rendering = { path = "../frame-rendering" }
frame-input = { path = "../frame-input" }
jni = "0.21"
ndk = "0.9"
ndk-sys = "0.6"
vello = "0.4"
raw-window-handle = "0.6"
log = "0.4"
android-activity = { version = "0.6", features = ["native-activity"] }
