[package]
name = "frame-macos"
version = "0.1.0"
edition = "2021"

[dependencies]
frame-core = { path = "../frame-core" }
frame-input = { path = "../frame-input" }
frame-rendering = { path = "../frame-rendering" }
slotmap = "1"
objc2 = "0.6"
objc2-foundation = { version = "0.3", features = ["NSThread"] }
objc2-app-kit = { version = "0.3", features = [
    "NSApplication",
    "NSRunningApplication",
    "NSWindow",
    "NSResponder",
    "NSGraphics",
    "NSView",
    "NSEvent",
] }
block2 = "0.6"
vello = "0.4"

[dev-dependencies]
frame-ui = { path = "../frame-ui" }
